<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/3/30 0030
 * Time: 17:18
 */

namespace app\admin\controller;


use app\common\controller\Backend;
use think\Db;

class Build extends Backend
{
    protected $model;
    public function _initialize()
    {
         parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = model('Build');
    }


    public function  index()
    {

        if ($this->request->isAjax()){
            list($where, $sort, $order, $offset, $limit) = $this->buildparams(null);

            $data['rows'] = $this->model->order(" $sort $order,release_time desc")->limit($offset,$limit)->select();

            $data['total'] = $this->model->count();

            return json($data);
        }

        return $this->view->fetch();

    }


    public function add()
    {
        if ($this->request->isAjax()){
            //验证token
            $this->token();
            $params = $this->request->post("row/a", []);

            $params['create_time'] = date('Y-m-d H:i:s');
            $params['title'] = trim($params['title']);

            $validate = validate('Build');
            if (!$validate->check($params)){
                $this->error($validate->getError());
            }
            $row = $this->model->insert($params);
            if ($row){
                $this->success();
            }else{
                $this->error();
            }
        }

        //获取数据库最大的排序值+1
        $row = $this->model->field('max(weigh) as max')->where('status',1)->find();

        $max = $row['max']+1;
        $this->assign('max',$max);
        return $this->view->fetch();
    }


    public function edit( $ids = '')
    {

        $row = $this->model->get(['id' => $ids]);
        //var_dump($row);die;
        if (!$row) {
            $this->error(__('No Results were found'));
        }
        if ($this->request->isPost()){

            $this->token();

            $params = $this->request->post("row/a", []);
            $params['title'] = trim($params['title']);
            $validate = validate('Build');
            if (!$validate->check($params)){
                $this->error($validate->getError());
            }

            $result = $row->where('id', $row->id)->update($params);
            // var_dump($result);die;
            if ($result === false) {
                $this->error($row->getError());
            }
            // Cache::rm('__menu__');
            $this->success();

        }

        $this->assign('row',$row);
        return $this->fetch();



    }


    public function del( $ids = '')
    {
        if ($ids) {
            $pk = $this->model->getPk();
            $adminIds = $this->getDataLimitAdminIds();
            if (is_array($adminIds)) {
                $this->model->where($this->dataLimitField, 'in', $adminIds);
            }
            $list = $this->model->where($pk, 'in', $ids)->select();

            $count = 0;
            Db::startTrans();
            try {
                foreach ($list as $k => $v) {
                    $count += $v->delete();
                }
                Db::commit();
            } catch (PDOException $e) {
                Db::rollback();
                $this->error($e->getMessage());
            } catch (Exception $e) {
                Db::rollback();
                $this->error($e->getMessage());
            }
            if ($count) {
                $this->success();
            } else {
                $this->error(__('No rows were deleted'));
            }
        }
        $this->error(__('Parameter %s can not be empty', 'ids'));
    }

}